//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Runtime.CompilerServices;
using Corvus.Json;

namespace Marain.Tenancy.ClientTenantProvider.TenancyClientSchemaTypes;
public readonly partial struct Resource
{
    public readonly partial struct EmbeddedEntity
    {
        public readonly partial struct AdditionalPropertiesEntity
        {
            /// <summary>
            /// A type generated from a JsonSchema specification.
            /// </summary>
            public readonly partial struct ResourceArray
            {
                /// <inheritdoc/>
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                public ResourceArray Remove(in JsonAny item1)
                {
                    return new(this.GetImmutableListWithout(item1));
                }

                /// <inheritdoc/>
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                public ResourceArray RemoveAt(int index)
                {
                    return new(this.GetImmutableListWithoutRange(index, 1));
                }

                /// <inheritdoc/>
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                public ResourceArray RemoveRange(int index, int count)
                {
                    return new(this.GetImmutableListWithoutRange(index, count));
                }
            }
        }
    }
}