//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using Corvus.Json;

namespace Marain.Tenancy.ClientTenantProvider.TenancyClientSchemaTypes;
/// <summary>
/// A type generated from a JsonSchema specification.
/// </summary>
public readonly partial struct Tenant
{
    /// <summary>
    /// Gets the value as a <see cref = "Marain.Tenancy.ClientTenantProvider.TenancyClientSchemaTypes.Resource"/>.
    /// </summary>
    public Marain.Tenancy.ClientTenantProvider.TenancyClientSchemaTypes.Resource AsResource
    {
        get
        {
            return (Marain.Tenancy.ClientTenantProvider.TenancyClientSchemaTypes.Resource)this;
        }
    }

    /// <summary>
    /// Gets a value indicating whether this is a valid <see cref = "Marain.Tenancy.ClientTenantProvider.TenancyClientSchemaTypes.Resource"/>.
    /// </summary>
    public bool IsResource
    {
        get
        {
            return ((Marain.Tenancy.ClientTenantProvider.TenancyClientSchemaTypes.Resource)this).IsValid();
        }
    }

    /// <summary>
    /// Gets the value as a <see cref = "Marain.Tenancy.ClientTenantProvider.TenancyClientSchemaTypes.Resource"/>.
    /// </summary>
    /// <param name = "result">The result of the conversion.</param>
    /// <returns><c>True</c> if the conversion was valid.</returns>
    public bool TryGetAsResource(out Marain.Tenancy.ClientTenantProvider.TenancyClientSchemaTypes.Resource result)
    {
        result = (Marain.Tenancy.ClientTenantProvider.TenancyClientSchemaTypes.Resource)this;
        return result.IsValid();
    }

    /// <summary>
    /// Gets the value as a <see cref = "Marain.Tenancy.ClientTenantProvider.TenancyClientSchemaTypes.Tenant.AnyOf1Entity"/>.
    /// </summary>
    public Marain.Tenancy.ClientTenantProvider.TenancyClientSchemaTypes.Tenant.AnyOf1Entity AsAnyOf1Entity
    {
        get
        {
            return (Marain.Tenancy.ClientTenantProvider.TenancyClientSchemaTypes.Tenant.AnyOf1Entity)this;
        }
    }

    /// <summary>
    /// Gets a value indicating whether this is a valid <see cref = "Marain.Tenancy.ClientTenantProvider.TenancyClientSchemaTypes.Tenant.AnyOf1Entity"/>.
    /// </summary>
    public bool IsAnyOf1Entity
    {
        get
        {
            return ((Marain.Tenancy.ClientTenantProvider.TenancyClientSchemaTypes.Tenant.AnyOf1Entity)this).IsValid();
        }
    }

    /// <summary>
    /// Gets the value as a <see cref = "Marain.Tenancy.ClientTenantProvider.TenancyClientSchemaTypes.Tenant.AnyOf1Entity"/>.
    /// </summary>
    /// <param name = "result">The result of the conversion.</param>
    /// <returns><c>True</c> if the conversion was valid.</returns>
    public bool TryGetAsAnyOf1Entity(out Marain.Tenancy.ClientTenantProvider.TenancyClientSchemaTypes.Tenant.AnyOf1Entity result)
    {
        result = (Marain.Tenancy.ClientTenantProvider.TenancyClientSchemaTypes.Tenant.AnyOf1Entity)this;
        return result.IsValid();
    }
}