//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using Corvus.Json;

namespace Marain.Tenancy.ClientTenantProvider.TenancyClientSchemaTypes;
public readonly partial struct UpdateTenantJsonPatchEntry
{
    /// <summary>
    /// A type generated from a JsonSchema specification.
    /// </summary>
    public readonly partial struct ValueEntity
    {
        private ValidationContext ValidateAnyOf(in ValidationContext validationContext, ValidationLevel level)
        {
            ValidationContext result = validationContext;
            if (level > ValidationLevel.Basic)
            {
                result = result.PushValidationLocationProperty("anyOf");
            }

            ValidationContext childContextBase = result;
            bool foundValid = false;
            ValidationContext childContext0 = childContextBase;
            if (level > ValidationLevel.Basic)
            {
                childContext0 = childContext0.PushValidationLocationArrayIndex(0);
            }

            ValidationContext anyOfResult0 = this.As<Corvus.Json.JsonString>().Validate(childContext0.CreateChildContext(), level);
            if (anyOfResult0.IsValid)
            {
                result = result.MergeChildContext(anyOfResult0, level >= ValidationLevel.Verbose);
                if (level == ValidationLevel.Flag)
                {
                    return result;
                }
                else
                {
                    foundValid = true;
                }
            }
            else
            {
                if (level >= ValidationLevel.Verbose)
                {
                    result = result.MergeResults(result.IsValid, level, anyOfResult0);
                }
            }

            ValidationContext childContext1 = childContextBase;
            if (level > ValidationLevel.Basic)
            {
                childContext1 = childContext1.PushValidationLocationArrayIndex(1);
            }

            ValidationContext anyOfResult1 = this.As<Corvus.Json.JsonObject>().Validate(childContext1.CreateChildContext(), level);
            if (anyOfResult1.IsValid)
            {
                result = result.MergeChildContext(anyOfResult1, level >= ValidationLevel.Verbose);
                if (level == ValidationLevel.Flag)
                {
                    return result;
                }
                else
                {
                    foundValid = true;
                }
            }
            else
            {
                if (level >= ValidationLevel.Verbose)
                {
                    result = result.MergeResults(result.IsValid, level, anyOfResult1);
                }
            }

            ValidationContext childContext2 = childContextBase;
            if (level > ValidationLevel.Basic)
            {
                childContext2 = childContext2.PushValidationLocationArrayIndex(2);
            }

            ValidationContext anyOfResult2 = this.As<Corvus.Json.JsonArray>().Validate(childContext2.CreateChildContext(), level);
            if (anyOfResult2.IsValid)
            {
                result = result.MergeChildContext(anyOfResult2, level >= ValidationLevel.Verbose);
                if (level == ValidationLevel.Flag)
                {
                    return result;
                }
                else
                {
                    foundValid = true;
                }
            }
            else
            {
                if (level >= ValidationLevel.Verbose)
                {
                    result = result.MergeResults(result.IsValid, level, anyOfResult2);
                }
            }

            ValidationContext childContext3 = childContextBase;
            if (level > ValidationLevel.Basic)
            {
                childContext3 = childContext3.PushValidationLocationArrayIndex(3);
            }

            ValidationContext anyOfResult3 = this.As<Corvus.Json.JsonBoolean>().Validate(childContext3.CreateChildContext(), level);
            if (anyOfResult3.IsValid)
            {
                result = result.MergeChildContext(anyOfResult3, level >= ValidationLevel.Verbose);
                if (level == ValidationLevel.Flag)
                {
                    return result;
                }
                else
                {
                    foundValid = true;
                }
            }
            else
            {
                if (level >= ValidationLevel.Verbose)
                {
                    result = result.MergeResults(result.IsValid, level, anyOfResult3);
                }
            }

            ValidationContext childContext4 = childContextBase;
            if (level > ValidationLevel.Basic)
            {
                childContext4 = childContext4.PushValidationLocationArrayIndex(4);
            }

            ValidationContext anyOfResult4 = this.As<Corvus.Json.JsonInteger>().Validate(childContext4.CreateChildContext(), level);
            if (anyOfResult4.IsValid)
            {
                result = result.MergeChildContext(anyOfResult4, level >= ValidationLevel.Verbose);
                if (level == ValidationLevel.Flag)
                {
                    return result;
                }
                else
                {
                    foundValid = true;
                }
            }
            else
            {
                if (level >= ValidationLevel.Verbose)
                {
                    result = result.MergeResults(result.IsValid, level, anyOfResult4);
                }
            }

            ValidationContext childContext5 = childContextBase;
            if (level > ValidationLevel.Basic)
            {
                childContext5 = childContext5.PushValidationLocationArrayIndex(5);
            }

            ValidationContext anyOfResult5 = this.As<Corvus.Json.JsonNumber>().Validate(childContext5.CreateChildContext(), level);
            if (anyOfResult5.IsValid)
            {
                result = result.MergeChildContext(anyOfResult5, level >= ValidationLevel.Verbose);
                if (level == ValidationLevel.Flag)
                {
                    return result;
                }
                else
                {
                    foundValid = true;
                }
            }
            else
            {
                if (level >= ValidationLevel.Verbose)
                {
                    result = result.MergeResults(result.IsValid, level, anyOfResult5);
                }
            }

            if (foundValid)
            {
                if (level >= ValidationLevel.Verbose)
                {
                    result = result.WithResult(isValid: true, "Validation 10.2.1.2. anyOf - validated against the anyOf schema.");
                }
            }
            else
            {
                if (level >= ValidationLevel.Detailed)
                {
                    result = result.WithResult(isValid: false, "Validation 10.2.1.2. anyOf - failed to validate against the anyOf schema.");
                }
                else if (level >= ValidationLevel.Basic)
                {
                    result = result.WithResult(isValid: false, "Validation 10.2.1.2. anyOf - failed to validate against the anyOf schema.");
                }
                else
                {
                    result = result.WithResult(isValid: false);
                }
            }

            if (level > ValidationLevel.Basic)
            {
                result = result.PopLocation(); // anyOf
            }

            return result;
        }
    }
}