FROM microsoft/dotnet:2.1-sdk AS installer-env
ARG PROJECT_FOLDER

COPY . /src/

RUN cd /src/${PROJECT_FOLDER} && \
    mkdir -p /home/site/wwwroot && \
    dotnet publish *.csproj --output /home/site/wwwroot

FROM mcr.microsoft.com/azure-functions/dotnet:2.0
ENV AzureWebJobsScriptRoot=/home/site/wwwroot

COPY --from=installer-env ["/home/site/wwwroot", "/home/site/wwwroot"]